version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-beeHelp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beeHelp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - beeHelp-network
  api:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: api-beeHelp
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/beeHelp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - beeHelp-network

volumes:
  postgres_data:

networks:
  beeHelp-network:
    driver: bridge
